### ISSUE TITLE
Cannot find module '__buttercup/classes/Archive.js'

### ISSUE THREAD

**Issue by Jameskmonger** [buttercup-pw/buttercup-core#70] opened 2016-03-22 00:43 UTC
![error message](https://cloud.githubusercontent.com/assets/4298089/13937731/ab2a87c4-ef9d-11e5-958b-765f08c3b61c.png)

@himynameisdave can you provide some more info on this?

**Comment by himynameisdave** [comment] 2016-03-22 00:55
:+1: yeah not too sure what's causing it.... I try to run `git-labelmaker` and I get this error.

Deleting `node_modules` in my global `git-labelmaker` pkg solves the issue

**Comment by perry-mitchell** [comment] 2016-03-22 05:03
This has to do with the symlink buttercup uses for locating files. Could you post your node and npm versions?

**Comment by Jameskmonger** [comment] 2016-03-22 09:35
I think I know the issue, @perry-mitchell. The links between source files (not just test to source files) are also using the symlink. This means that the symlink script needs to always work properly for the source to work. It'd probably be safer to use internal relative links when going from source to source. I'll submit a PR.

**Comment by Jameskmonger** [comment] 2016-03-22 09:52
Please see #71

**Comment by perry-mitchell** [comment] 2016-03-22 10:10
I'd like to avoid using rel links - the absolute paths work well downstream with Browserify which is one of the main users of buttercup core.

We should find what's causing the issue, as this isn't an issue in other projects.

**Comment by Jameskmonger** [comment] 2016-03-22 11:29
Okay, that's fine with me. I'm not able to replicate the issue locally. @himynameisdave, could you zip up your exact git-labelmaker folder (including node_modules) and upload it to Google Drive or something similar? It'd be good to be able to inspect it properly.

**Comment by himynameisdave** [comment] 2016-03-22 14:13
@Jameskmonger  Yep, here ya go: 
[`git-labelmaker.zip`](https://drive.google.com/a/velunny.com/file/d/0B_ONqac3bvmuWWVkd3l5dHJwcms/view?usp=sharing)

**Comment by himynameisdave** [comment] 2016-03-23 14:20
@perry-mitchell @Jameskmonger status?

**Comment by Jameskmonger** [comment] 2016-03-23 15:07
I'm able to reproduce it using your `.zip` and will look into it later @himynameisdave :smile:

**Comment by Jameskmonger** [comment] 2016-03-23 15:09
@perry-mitchell I think I'm beginning to understand the problem.

The `node_modules/buttercup/node_modules` folder has a single file in it (not a symlink) called `__buttercup`, which contains the following contents:

    ../source

It appears to be treating it as a file rather than as a symlink.

**Comment by perry-mitchell** [comment] 2016-03-23 15:16
That may be because it was zipped or OS differences. I'm not well versed in the low level configuration that a symlink goes through when it's created.

Dave could you share your current node setup, versions etc? Npm should look in node_modules for the path specified (__buttercup symlink points from there to source). Perhaps you could send the output of `ls -la` from within node_modules too.

**Comment by himynameisdave** [comment] 2016-03-23 16:17
Thanks for looking into this guys, let me know if you need anything from me

**Comment by perry-mitchell** [comment] 2016-03-23 18:08
@himynameisdave Also, as I'm waiting for access to be granted to your archive, would you mind telling us what version of Buttercup is installed in your labelmaker clone? There were problems with symlinks in a couple of versions prior to the current, so we should ensure you're up to date.

**Comment by himynameisdave** [comment] 2016-03-23 18:37
@perry-mitchell I believe it's `0.17.0` and you should have access now

**Comment by perry-mitchell** [comment] 2016-03-24 20:15
That's strange.. on my machine (Ubuntu 14.04), unzipping your archive leaves me with a correct-looking copy of buttercup in your labelmaker's node_modules:

```
perry@nostromo:~/Temp/git-labelmaker-compress/node_modules/buttercup/node_modules$ ll
total 12
drwxr-xr-x 2 perry perry 4096 maali 24 22:10 ./
drwxr-xr-x 8 perry perry 4096 maali 24 22:10 ../
lrwxrwxrwx 1 perry perry    9 maali 24 22:10 __buttercup -> ../source/
perry@nostromo:~/Temp/git-labelmaker-compress/node_modules/buttercup/node_modules$ cd __buttercup
perry@nostromo:~/Temp/git-labelmaker-compress/node_modules/buttercup/node_modules/__buttercup$ ls
classes  data  encryption  module.js  tools
```

**Comment by himynameisdave** [comment] 2016-03-28 00:05
Done all that, haven't been able to reproduce this issue since doing it so *maybe* that fixed things? 

Thanks guys

**Comment by perry-mitchell** [comment] 2016-09-25 16:53
As we're no longer using symlinks, I'm closing this issue (ref: [rel links](https://github.com/buttercup-pw/buttercup-core/blob/master/source/module.js#L7)). Please submit a new issue if the problem still occurs.

**Closed by perry-mitchell** 2016-09-25 16:53 UTC
